import LoginPage from "./pages/Login.jsx";
import SignupPage from "./pages/Signup.jsx";
import Home from "./pages/Home.jsx";
import CreateProduct from './pages/createProduct.jsx';
import MyProducts from "./pages/myProducts.jsx";
import Cart from "./pages/cart.jsx";
import ProductDetails from "./pages/productdetails.jsx";
import Profile from "./pages/profile.jsx";
import CreateAddress from "./pages/createAddress.jsx";
export {LoginPage,SignupPage,Home,CreateProduct, MyProducts, Cart, ProductDetails, Profile, CreateAddress};